language: python
python:
  - "3.6"
install: "pip install -r requirements.txt -r requirements-dev.txt"
#before_script:
#  - cp .env.example .env
#  - python manage.py migrate
script:
  - flake8
  - mypy --ignore-missing-imports .
  - nosetests
after_success:
  codecov
